services:
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}  # database name
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    container_name: 'redis'
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  web:
    container_name: 'spring-docker'
    build: ./
    #    image: spring-docker-jar:latest
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_SQL_INIT_MODE: never
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}


volumes:
  pgdata:
  redis_data:
