services:
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_DB: forum_db  # 設定要建立的資料庫名稱
      POSTGRES_USER: root    # 設定使用者名稱
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    container_name: 'spring-docker-demo'
    build: ./
#    image: spring-docker-jar:latest
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MAIL_USERNAME: outrunner234@gmail.com
      MAIL_PASSWORD: qrbaerrhltxphshz

volumes:
  pgdata:
