package com.java.forum.dao;

import com.java.forum.entity.User;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Repository;

@Repository
public class UserDaoImpl implements UserDao {

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    public User selectById(int id) {
        return entityManager.find(User.class, id);
    }

    @Override
    public User selectByName(String username) {
        return entityManager.createQuery("SELECT u FROM User u WHERE u.username = :username", User.class)
                .setParameter("username", username)
                .getSingleResult();
    }

    @Override
    public User selectByEmail(String email) {
        return entityManager.createQuery("SELECT u FROM User u WHERE u.email=:email", User.class)
                .setParameter("email", email)
                .getSingleResult();
    }

    @Override
    @Transactional
    public int insertUser(User user) {      //no  need id (autogenerated)
        entityManager.persist(user);
        return user.getId();
        }

    @Override
    @Transactional
    public int updateStatus(int id, int status) {
        User user = entityManager.find(User.class,id);
        if (user != null){
            user.setStatus(status);
            entityManager.merge(user);
            return 1;
        }
        return 0;
    }

    @Override
    public int updateHeader(int id, String headerUrl) {
        return 0;
    }

    @Override
    public int updatePassword(int id, String password) {
        return 0;
    }
}
